project:
  type: website 
  output-dir: docs

website:
  title: "Adam L. Ozer, Ph.D."
  navbar:
    right:
      - href: blog/index.qmd
        text: Blog
      - href: https://drive.google.com/file/d/1Qjok1SjCKTVaR0I15d9rqvYEfcHBUf-y/view
        text: CV
        icon: link
      - href: publications.qmd
        text: Publications

  page-footer:  
    left: >-
     &#169; 2024 Adam Ozer &#8729; Made with [Quarto](https://quarto.org)

    right: 
      - text: Contact
        aria-label: Contact Form
        href: contact.qmd
      - text: License
        aria-label: License Details
        href: license.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

