---
title: "<span style='font-family: Lora;'>Project portfolio</span>"
format:
  html:
    toc: true
    css: publications_theme.css
description: "<span style='font-family: Calibri;'>A selection of works in social science, data science, and everything in between.</span>"
fontsize: 1.2rem
mainfont: "Calibri"
---

<br/>

## Social Research Projects {{< fa lightbulb >}}

-   [The UK MP Inbox](https://ukmpinbox.shinyapps.io/uk_mp_inbox/) - A comprehensive database of thousands email newsletters sent by UK members of parliament.

- [Understanding Pupil Premium spending in schools](https://educationendowmentfoundation.org.uk/projects-and-evaluation/projects/pupil-premium-statement-research-project) - Commissioned by the *Education Endowment Fund (EEF)*, this project aims to assess how UK schools report spending their Pupil Premium funding.

- [R&D Science and Analysis Programme - Capturing engagement numbers](https://www.gov.uk/government/collections/rd-science-and-analysis-programme-capturing-engagement-numbers) - Commissioned by the *Department for Culture, Media, and Sport (DCMS)*, this project explores different methodologies for measuring public engagement in different cultural and sporting activities.

## Data Science Training & Mentoring {{< fa brain >}}

-   **Verian Global Data Science Training seminar** - an annual internal seminar aimed at educating early career researchers about key DS principles and tools.

-   **Introduction to R Workshop Series** - an annual series of beginner-friendly workshops covering the basics of data wrangling and data visualisation.

## Selected Academic Publications {{< fa file-pen >}}

-   **Ozer, Adam L.**, Waggoner, Philip D., & Kennedy, Ryan. 2024. “The Paradox of Algorithms and Blame on Public Decision-makers”. *Business and Politics*.  [**https://doi.org/10.1017/bap.2023.35**](https://doi.org/10.1017/bap.2023.35)

-   **Ozer, Adam L.** 2023. “Women Experts and Gender Bias in Political Media”. *Public Opinion Quarterly*.  [**https://doi.org/10.1093/poq/nfad011**](https://doi.org/10.1093/poq/nfad011)

-   **Ozer, Adam L.** & Wright, Jamie. 2022. “Partisan News Versus Party Cues: The Effect of Cross-Cutting Party and Partisan Network Cues on Polarization and Persuasion”. *Research & Politics.*  [**https://doi.org/10.1177/20531680221075455**](https://doi.org/10.1177/20531680221075455)

-   **Ozer, Adam L.**, Sullivan, Brian W.,  & Van, Douglas S. 2022.  "Viewed from Different Engels? Differences in Reactions to “Socialism” as a Policy Label". *Political Research Quarterly*.  [**https://doi.org/10.1177/10659129211037402**](https://doi.org/10.1177/10659129211037402)

-   Simas, Elizabeth N. & **Ozer, Adam L.** 2021. “Polarization, candidate positioning, and political participation in the U.S.”. *Electoral Studies*, 73. [**https://doi.org/10.1016/j.electstud.2021.102370**](https://doi.org/10.1016/j.electstud.2021.102370)

-   **Ozer, Adam L.** 2020. "Well, you’re the expert: how signals of source expertise help mitigate partisan bias." *Journal of Elections, Public Opinion and Parties*, 1-21. [**https://doi.org/10.1080/17457289.2020.1744611**](https://doi.org/10.1080/17457289.2020.1744611)
